
services:
  coder-server:
    build: .
    image: codercom/code-server:latest
    container_name: coder-server
    ports:
      - "8080:8080"
    volumes:
      - coder-data:/home/coder 
    environment:
      - PASSWORD=Wincom2025!
    user: "0:0"  # Run as root user
volumes:
  coder-data:
